on:
  push:
    branches:
      - master





jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'before folder content'
        run: ls

      - uses: actions/checkout@v3  

      - name: 'after folder content'
        run: ls



      
